import dotenv from "dotenv";
import dbConnect from "../config/databaseConfig.js";
import CategoryPricing from "../models/categoryPricingModel.js";

dotenv.config();
await dbConnect();

const seed = [

  {
    category: "PROPERTY",
    subcategory: null,
    label: "Property Default",
    publishPrice: 3499,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "LAND",
    subcategory: null,
    label: "Land Default",
    publishPrice: 3499,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "VEHICLES",
    subcategory: null,
    label: "Vehicles Default",
    publishPrice: 2499,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "PHONES",
    subcategory: null,
    label: "Phones Default",
    publishPrice: 1499,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "ELECTRONICS",
    subcategory: null,
    label: "Electronics Default",
    publishPrice: 1999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "HOME",
    subcategory: null,
    label: "Home Default",
    publishPrice: 1599,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "BABY",
    subcategory: null,
    label: "Baby Default",
    publishPrice: 1799,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "SPORTS_FITNESS",
    subcategory: null,
    label: "Sports & Fitness Default",
    publishPrice: 1999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "AGRICULTURE",
    subcategory: null,
    label: "Agriculture Default",
    publishPrice: 1999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "FOOD",
    subcategory: null,
    label: "Food Default",
    publishPrice: 1999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "PETS_ANIMALS",
    subcategory: null,
    label: "Pets Default",
    publishPrice: 1999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "TOYS_GAMES",
    subcategory: null,
    label: "Toys Default",
    publishPrice: 1999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "FASHION",
    subcategory: null,
    label: "Fashion Default",
    publishPrice: 1999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "MEN_FASHION",
    subcategory: null,
    label: "Fashion Default",
    publishPrice: 1999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "WOMEN_FASHION",
    subcategory: null,
    label: "Fashion Default",
    publishPrice: 1999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },

  {
    category: "EDUCATION",
    subcategory: null,
    label: "Education Default",
    publishPrice: 1300,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "SERVICES",
    subcategory: null,
    label: "Services Default",
    publishPrice: 1600,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "JOBS",
    subcategory: null,
    label: "Jobs Default",
    publishPrice: 1000,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "INDUSTRIAL_TOOLS",
    subcategory: null,
    label: "Industrial Tools Default",
    publishPrice: 2300,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },

  {
    category: "PROPERTY",
    subcategory: "HOUSE",
    label: "House",
    publishPrice: 3499,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "PROPERTY",
    subcategory: "APARTMENT",
    label: "Apartment",
    publishPrice: 3499,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "PROPERTY",
    subcategory: "DUPLEX",
    label: "Duplex",
    publishPrice: 3999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "PROPERTY",
    subcategory: "MANSION",
    label: "Mansion",
    publishPrice: 4500,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: false,
    isActive: true,
  },
  {
    category: "PROPERTY",
    subcategory: "SHOP",
    label: "Shop",
    publishPrice: 4500,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "PROPERTY",
    subcategory: "OFFICE_SPACE",
    label: "Office Space",
    publishPrice: 4500,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "PROPERTY",
    subcategory: "WAREHOUSE",
    label: "Warehouse",
    publishPrice: 4500,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: false,
    isActive: true,
  },
  {
    category: "PROPERTY",
    subcategory: "FACTORY",
    label: "Factory",
    publishPrice: 4500,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: false,
    isActive: true,
  },
  {
    category: "PROPERTY",
    subcategory: "HOTEL",
    label: "Hotel",
    publishPrice: 4500,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: false,
    isActive: true,
  },
  {
    category: "PROPERTY",
    subcategory: "EVENT_CENTER",
    label: "Event Center",
    publishPrice: 4500,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: false,
    isActive: true,
  },
  {
    category: "PROPERTY",
    subcategory: "COMMERCIAL_BUILDING",
    label: "Commercial Building",
    publishPrice: 4500,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: false,
    isActive: true,
  },

  {
    category: "LAND",
    subcategory: "RESIDENTIAL_PLOT",
    label: "Residential Plot",
    publishPrice: 3499,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "LAND",
    subcategory: "COMMERCIAL_PLOT",
    label: "Commercial Plot",
    publishPrice: 4500,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "LAND",
    subcategory: "INDUSTRIAL_LAND",
    label: "Industrial Land",
    publishPrice: 4500,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: false,
    isActive: true,
  },

  {
    category: "VEHICLES",
    subcategory: "CARS",
    label: "Cars",
    publishPrice: 2499,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "VEHICLES",
    subcategory: "TRUCKS",
    label: "Trucks",
    publishPrice: 2800,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "VEHICLES",
    subcategory: "BUSES",
    label: "Buses",
    publishPrice: 2700,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },

  {
    category: "PHONES",
    subcategory: "SMART_PHONES",
    label: "Smart Phones",
    publishPrice: 1499,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "PHONES",
    subcategory: "SMART_WATCHES",
    label: "Smart Watches",
    publishPrice: 1999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "PHONES",
    subcategory: "BUTTON_PHONES",
    label: "Button Phones",
    publishPrice: 1200,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "PHONES",
    subcategory: "TABLETS",
    label: "Tablets",
    publishPrice: 1800,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "PHONES",
    subcategory: "MOBILE_ACCESSORIES",
    label: "Mobile Accessories",
    publishPrice: 1300,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },

  {
    category: "ELECTRONICS",
    subcategory: "GAMING_CONSOLES",
    label: "Gaming Consoles",
    publishPrice: 1999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },

  {
    category: "FOOD",
    subcategory: "BEVERAGES",
    label: "Beverages",
    publishPrice: 1300,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "FOOD",
    subcategory: "FRESH_FOOD",
    label: "Fresh Food",
    publishPrice: 1500,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "FOOD",
    subcategory: "MEAT_SEAFOOD",
    label: "Meat & Seafood",
    publishPrice: 1700,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },

  {
    category: "EDUCATION",
    subcategory: "COURSES",
    label: "Courses",
    publishPrice: 1800,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "EDUCATION",
    subcategory: "STUDY_MATERIALS",
    label: "Study Materials",
    publishPrice: 1300,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },

  {
    category: "SERVICES",
    subcategory: "HOME_SERVICES",
    label: "Home Services",
    publishPrice: 1600,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "SERVICES",
    subcategory: "BEAUTY_SERVICES",
    label: "Beauty Services",
    publishPrice: 1400,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "SERVICES",
    subcategory: "TECH_SERVICES",
    label: "Tech Services",
    publishPrice: 1900,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "SERVICES",
    subcategory: "AUTO_SERVICES",
    label: "Auto Services",
    publishPrice: 1700,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "SERVICES",
    subcategory: "BUSINESS_SERVICES",
    label: "Business Services",
    publishPrice: 2000,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "SERVICES",
    subcategory: "CONSTRUCTION_SERVICES",
    label: "Construction Services",
    publishPrice: 2200,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "SERVICES",
    subcategory: "DELIVERY_LOGISTICS",
    label: "Delivery & Logistics",
    publishPrice: 1800,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },

  {
    category: "JOBS",
    subcategory: "DOMESTIC_HELP",
    label: "Domestic Help",
    publishPrice: 1000,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "JOBS",
    subcategory: "BEAUTY_FASHION_WORKERS",
    label: "Beauty & Fashion Workers",
    publishPrice: 1000,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "JOBS",
    subcategory: "CAREGIVERS_NANNIES",
    label: "Caregivers & Nannies",
    publishPrice: 1100,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "JOBS",
    subcategory: "DRIVERS_LOGISTICS",
    label: "Drivers & Logistics",
    publishPrice: 1200,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "JOBS",
    subcategory: "ARTISANS_TECHNICIANS",
    label: "Artisans & Technicians",
    publishPrice: 1200,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },

  {
    category: "INDUSTRIAL_TOOLS",
    subcategory: "POWER_TOOLS",
    label: "Power Tools",
    publishPrice: 2300,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "INDUSTRIAL_TOOLS",
    subcategory: "HAND_TOOLS",
    label: "Hand Tools",
    publishPrice: 2100,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "INDUSTRIAL_TOOLS",
    subcategory: "WELDING_EQUIPMENT",
    label: "Welding Equipment",
    publishPrice: 2200,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: false,
    isActive: true,
  },
];

for (const item of seed) {
  await CategoryPricing.updateOne(
    {
      category: item.category,
      subcategory: item.subcategory,
    },
    {
      $set: {
        ...item,
        isActive: true,
      },
    },
    { upsert: true }
  );
}

console.log("✅ Category & subcategory pricing seeded");
process.exit(0);