import dotenv from "dotenv";
import dbConnect from "../config/databaseConfig.js";
import CategoryPricing from "../models/categoryPricingModel.js";

dotenv.config();
await dbConnect();

const seed = [
  // CATEGORY DEFAULTS
  {
    category: "PROPERTY",
    subcategory: null,
    label: "Property Default",
    publishPrice: 3499,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "VEHICLES",
    subcategory: null,
    label: "Vehicles Default",
    publishPrice: 2499,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "PHONES",
    subcategory: null,
    label: "Phones Default",
    publishPrice: 1499,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "ELECTRONICS",
    subcategory: null,
    label: "Electronics Default",
    publishPrice: 1999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "HOME",
    subcategory: null,
    label: "Home Default",
    publishPrice: 1599,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "BABY",
    subcategory: null,
    label: "Baby Default",
    publishPrice: 1799,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "SPORTS_FITNESS",
    subcategory: null,
    label: "Sports & Fitness Default",
    publishPrice: 1999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "AGRICULTURE",
    subcategory: null,
    label: "Agriculture Default",
    publishPrice: 1999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "FOOD",
    subcategory: null,
    label: "Food Default",
    publishPrice: 1999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "PETS_ANIMALS",
    subcategory: null,
    label: "Pets & Animals Default",
    publishPrice: 1999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "TOYS_GAMES",
    subcategory: null,
    label: "Toys & Games Default",
    publishPrice: 1999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "FASHION",
    subcategory: null,
    label: "Fashion Default",
    publishPrice: 1999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },

  // SUBCATEGORY OVERRIDES
  {
    category: "PROPERTY",
    subcategory: "HOUSES_APARTMENTS",
    label: "Houses & Apartments",
    publishPrice: 3499,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "PROPERTY",
    subcategory: "LANDS_PLOTS",
    label: "Lands & Plots",
    publishPrice: 3499,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "VEHICLES",
    subcategory: "TRUCKS_TRAILERS",
    label: "Trucks & Trailers",
    publishPrice: 2499,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "VEHICLES",
    subcategory: "CARS",
    label: "Cars",
    publishPrice: 2499,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "PHONES",
    subcategory: "SMART_PHONES",
    label: "Smart Phones",
    publishPrice: 1499,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "PHONES",
    subcategory: "SMART_WATCHES",
    label: "Smart Watches",
    publishPrice: 1999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
  {
    category: "ELECTRONICS",
    subcategory: "GAMING_CONSOLES",
    label: "Gaming Consoles",
    publishPrice: 1999,
    trialDays: 14,
    paidDays: 30,
    trialEnabled: true,
    isActive: true,
  },
];

for (const item of seed) {
  await CategoryPricing.updateOne(
    {
      category: item.category,
      subcategory: item.subcategory,
    },
    {
      $set: {
        ...item,
        isActive: true,
      },
    },
    { upsert: true }
  );
}

console.log("✅ Category & subcategory pricing seeded");
process.exit(0);